model:
  d_model: 256
  n_heads: 4
  depth: 4
  patch_len: 32
  stride: 16
train:
  epochs: 150
  batch_size: 64
  backbone_lr: 0.0001
  head_lr: 0.0003
  weight_decay: 0.05
  pretrained: checkpoints/ssl_ppt.ckpt
  num_workers: 0
  mil_variant: attention
  topk_k: 5
  early_stop_patience: 20
  max_grad_norm: 1.0
  label_smoothing: 0.05
  aug:
    jitter_std: 0.018
    time_shift: 8
    scale_std: 0.06
  mil:
    activation: softmax 
    temperature: 1.1
    learnable_tau: false
    time_aware:
      enable: false
      mode: relbias            # relbias | concat
      max_patches: 64
      d_pos: 8                # mode=concat のときのみ使用     
  adr:
    enable: false
    weight: 0.005 